name: elongationnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - captum
  - pytorch
  - numpy
  - pandas
  - wandb
  - matplotlib
  - scikit-learn  # sklearn is installed via scikit-learn
  - seaborn
  - logomaker
  - natsort
  - pybigwig
  - pip
  - pip:
      - pickle  # only needed if you're using an extra pickle package (not common)

